"""
WebRTC Audio Bridge Daemon — aiohttp + aiortc server.

This daemon runs alongside Apache and Asterisk on the ASL3 node.
It provides:

- WebSocket endpoint at ``/ws`` for PTT signaling and audio relay
- WebRTC peer connection at ``/webrtc`` (aiortc)
- Health check at ``/health`` returning ``{"status":"ok"}``
- IAX2 registration and call management via ``IAX2Session``

Configuration
-------------
All values are read from environment variables:

========================  =================  ======  ===========================
Variable                 Default            Required Description
========================  =================  ======  ===========================
WEBRTC_PORT              9091               No       HTTP/WS listen port
IAX_HOST                 127.0.0.1          No       Asterisk IAX2 bind address
IAX_PORT                 4569               No       Asterisk IAX2 UDP port
IAX_PHONE_USER           webrtc-bridge      No       IAX2 extension username
IAX_PHONE_PASS           —                  Yes      IAX2 extension secret
WEBRTC_SECRET            —                  Yes      HMAC secret for WS auth
ASL_NODE                 494780             No       Local ASL node number
LOG_LEVEL                INFO               No       Python log level
========================  =================  ======  ===========================

Startup
-------
    python -m app.Services.WebRTCBridge.server

Or directly:

    python server.py
"""

from __future__ import annotations

import asyncio
import hmac
import json
import logging
import os
import sys
from typing import Any, Optional

import aiohttp
from aiohttp import web

from app.Services.WebRTCBridge.iax2 import IAX2Session
from app.Services.WebRTCBridge.audio import tx_process, rx_process

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

logging.basicConfig(
    level=os.environ.get("LOG_LEVEL", "INFO").upper(),
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger("webrtc-bridge")

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

# aiortc is optional — the server starts without it (health + WS only)
_has_aiortc = False
try:
    import aiortc  # noqa: F401 — ensure importable
    _has_aiortc = True
except ImportError:
    logger.warning("aiortc not available — WebRTC endpoint disabled")


def _env_str(key: str, default: str = "") -> str:
    return os.environ.get(key, default)


def _env_int(key: str, default: int) -> int:
    try:
        return int(os.environ.get(key, str(default)))
    except (ValueError, TypeError):
        return default


class BridgeConfig:
    """Daemon configuration, loaded from environment variables."""

    def __init__(self) -> None:
        self.webrtc_port: int = _env_int("WEBRTC_PORT", 9091)
        self.iax_host: str = _env_str("IAX_HOST", "127.0.0.1")
        self.iax_port: int = _env_int("IAX_PORT", 4569)
        self.iax_user: str = _env_str("IAX_PHONE_USER", "webrtc-bridge")
        self.iax_pass: str = _env_str("IAX_PHONE_PASS", "")
        self.webrtc_secret: str = _env_str("WEBRTC_SECRET", "")
        self.asl_node: str = _env_str("ASL_NODE", "494780")

    def validate(self) -> list[str]:
        """Return list of missing required config items."""
        errors: list[str] = []
        if not self.iax_pass:
            errors.append("IAX_PHONE_PASS is required")
        if not self.webrtc_secret:
            errors.append("WEBRTC_SECRET is required")
        return errors


# ---------------------------------------------------------------------------
# Bridge Application
# ---------------------------------------------------------------------------

class WebRTCBridgeApp:
    """Main bridge application — ties IAX2, WebSocket, and WebRTC together."""

    def __init__(self, config: BridgeConfig) -> None:
        self.config = config
        self.iax: IAX2Session = IAX2Session(
            host=config.iax_host,
            port=config.iax_port,
            username=config.iax_user,
            password=config.iax_pass,
        )

        # Connected WebSocket peers
        self._ws_peers: set[web.WebSocketResponse] = set()
        self._ws_auth_token: Optional[str] = None

        # PTT state
        self._ptt_active: bool = False
        self._call_active: bool = False

        # Audio forwarding tasks
        self._ws_recv_task: Optional[asyncio.Task[None]] = None

        # Wire IAX2 callbacks
        self.iax.on_audio_frame = self._on_iax_audio
        self.iax.on_disconnect = self._on_iax_disconnect

    # -- Auth --

    def validate_ws_token(self, token: str) -> bool:
        """Validate a WebSocket HMAC token.

        Tokens are generated by the PHP endpoint ``/api/ptt-ws-token.php``
        using the same ``WEBRTC_SECRET``.
        """
        if not self.config.webrtc_secret:
            return False
        # Token format: "<username>:<hex_signature>"
        parts = token.split(":", 1)
        if len(parts) != 2:
            return False
        _username, signature = parts

        expected = hmac.new(
            self.config.webrtc_secret.encode("utf-8"),
            _username.encode("utf-8"),  # message = username only
            "sha256",
        ).hexdigest()[:16]  # first 16 hex chars

        # Constant-time comparison
        return hmac.compare_digest(signature, expected[: len(signature)])

    # -- IAX2 Audio Callback --

    async def _on_iax_audio(self, ulaw_payload: bytes) -> None:
        """Forward received ulaw audio from Asterisk to all WS peers."""
        if not self._ws_peers:
            return

        try:
            # RX pipeline: ulaw → PCM s16le → upscale to 16 kHz → float32
            pcm_f32 = rx_process(ulaw_payload)
            msg = json.dumps({
                "type": "audio",
                "data": pcm_f32.hex(),
                "rate": 16000,
            })
            for ws in list(self._ws_peers):
                try:
                    await ws.send_str(msg)
                except ConnectionResetError:
                    self._ws_peers.discard(ws)
        except Exception as exc:
            logger.exception("Audio RX callback error: %s", exc)

    async def _on_iax_disconnect(self) -> None:
        """Handle remote HANGUP from Asterisk — reset call state."""
        logger.info("IAX2 disconnect received — resetting call state")
        self._call_active = False
        self._ptt_active = False
        await self._broadcast_status()

    # -- PTT Handlers --

    async def _ptt_key(self) -> None:
        """Key the transmitter via DTMF *99.

        If no active call, first place the call to the ASL node.
        """
        if not self.iax.is_registered:
            logger.warning("PTT key ignored: IAX2 not registered")
            return

        if not self._call_active:
            logger.info("Placing IAX2 call to node %s", self.config.asl_node)
            try:
                await self.iax.start_call(self.config.asl_node)
                self._call_active = True
            except (TimeoutError, RuntimeError) as exc:
                logger.error("Call setup failed: %s", exc)
                return

        # Send DTMF *99 to key
        logger.debug("PTT key: sending *99")
        self.iax.send_dtmf_string("*99")
        self._ptt_active = True

        # Broadcast PTT status
        await self._broadcast_status()

    async def _ptt_unkey(self) -> None:
        """Unkey the transmitter via DTMF #."""
        if not self._ptt_active:
            return

        logger.debug("PTT unkey: sending #")
        self.iax.send_dtmf("#")
        self._ptt_active = False

        # Hang up the call after a brief delay to let the # propagate
        if self._call_active:
            await asyncio.sleep(0.2)
            await self.iax.hangup_call()
            self._call_active = False

        await self._broadcast_status()

    async def _broadcast_status(self) -> None:
        """Send current bridge status to all connected WS peers."""
        status = {
            "type": "status",
            "registered": self.iax.is_registered,
            "in_call": self._call_active,
            "ptt_active": self._ptt_active,
        }
        msg = json.dumps(status)
        for ws in list(self._ws_peers):
            try:
                await ws.send_str(msg)
            except ConnectionResetError:
                self._ws_peers.discard(ws)

    # -- WebSocket Handler --

    async def handle_ws(self, request: web.Request) -> web.StreamResponse:
        """WebSocket handler at ``/ws``.

        Query parameter ``token`` (HMAC) is required for authentication.
        """
        token = request.query.get("token", "")
        if not self.validate_ws_token(token):
            logger.warning("WS connection rejected: invalid token")
            return web.json_response(
                {"error": "invalid token"}, status=401
            )

        ws = web.WebSocketResponse()
        await ws.prepare(request)
        self._ws_peers.add(ws)
        logger.info("WS client connected (%d peers)", len(self._ws_peers))

        # Send initial status
        await self._broadcast_status()

        try:
            async for msg in ws:
                if msg.type == aiohttp.WSMsgType.TEXT:
                    await self._handle_ws_message(ws, msg.data)
                elif msg.type == aiohttp.WSMsgType.ERROR:
                    logger.error("WS error: %s", ws.exception())
        except asyncio.CancelledError:
            pass
        finally:
            self._ws_peers.discard(ws)
            logger.info("WS client disconnected (%d peers)", len(self._ws_peers))

            # If no more peers, hang up
            if not self._ws_peers and self._ptt_active:
                await self._ptt_unkey()

        return ws

    async def _handle_ws_message(
        self, ws: web.WebSocketResponse, data: str
    ) -> None:
        """Route incoming WebSocket messages."""
        try:
            payload: dict[str, Any] = json.loads(data)
        except json.JSONDecodeError:
            logger.warning("Invalid WS JSON: %.80s", data)
            return

        msg_type = payload.get("type", "")

        if msg_type == "ptt":
            action = payload.get("action", "")
            if action == "key":
                await self._ptt_key()
            elif action == "unkey":
                await self._ptt_unkey()

        elif msg_type == "audio_tx":
            # Transmit audio: hex-encoded float32 PCM 16 kHz from browser
            try:
                pcm_f32_hex = payload.get("data", "")
                if pcm_f32_hex:
                    pcm_f32 = bytes.fromhex(pcm_f32_hex)
                    ulaw = tx_process(pcm_f32)
                    self.iax.send_voice(ulaw)
            except (ValueError, KeyError) as exc:
                logger.warning("audio_tx parse error: %s", exc)

        else:
            logger.debug("Unknown WS message type: %s", msg_type)

    # -- Health Endpoint --

    async def handle_health(self, request: web.Request) -> web.Response:
        """Return bridge health status as JSON.

        Always responds 200 — the PHP status proxy uses this.
        """
        return web.json_response({
            "status": "ok",
            "registered": self.iax.is_registered,
            "in_call": self._call_active,
            "ptt_active": self._ptt_active,
            "peers": len(self._ws_peers),
        })

    # -- Application Factory --

    def create_app(self) -> web.Application:
        """Build the aiohttp application."""
        app = web.Application()

        app.router.add_get("/health", self.handle_health)
        app.router.add_get("/ws", self.handle_ws)

        if _has_aiortc:
            # WebRTC endpoint would go here in future phases
            logger.info("aiortc available — WebRTC endpoint ready")
        else:
            logger.info("aiortc not installed — WebRTC disabled")

        # Store app reference for cleanup
        app["bridge"] = self

        return app


# ---------------------------------------------------------------------------
# Startup / Shutdown
# ---------------------------------------------------------------------------

async def _on_startup(app: web.Application) -> None:
    """Connect and register IAX2 on application startup."""
    bridge: WebRTCBridgeApp = app["bridge"]
    logger.info("Starting WebRTC Audio Bridge v0.1.0")

    try:
        await bridge.iax.connect()
        await bridge.iax.register()
        logger.info("IAX2 registered successfully")
    except (ConnectionError, PermissionError, TimeoutError) as exc:
        logger.error("IAX2 startup failed: %s", exc)
        # Don't crash — health endpoint will show not-registered


async def _on_shutdown(app: web.Application) -> None:
    """Cleanly tear down IAX2 on shutdown."""
    bridge: WebRTCBridgeApp = app["bridge"]
    logger.info("Shutting down WebRTC Audio Bridge")
    await bridge.iax.close()


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------

def main() -> None:
    """Parse config, build app, and run the aiohttp server."""
    config = BridgeConfig()
    errors = config.validate()
    if errors:
        for err in errors:
            logger.error("Config error: %s", err)
        sys.exit(1)

    bridge = WebRTCBridgeApp(config)
    app = bridge.create_app()

    app.on_startup.append(_on_startup)
    app.on_shutdown.append(_on_shutdown)

    logger.info(
        "Listening on 0.0.0.0:%d — health at /health, WS at /ws",
        config.webrtc_port,
    )

    web.run_app(app, host="0.0.0.0", port=config.webrtc_port)


if __name__ == "__main__":
    main()
