<?php
declare(strict_types=1);

/**
 * public/api/companion-download.php
 * -----------------------------------------------
 * Descarga el Companion App con configuración pre-instalada.
 *
 * Flujo:
 *   1. Valida sesión
 *   2. Obtiene la IP de la Pi
 *   3. Genera config.toml con la IP correcta
 *   4. Retorna el .exe con el config incluido
 * -----------------------------------------------
 */

require_once __DIR__ . '/../../config/app.php';
require_once ROOT_PATH . '/app/autoload.php';

use App\Auth\Auth;

header('Content-Type: application/octet-stream');
header('Content-Disposition: attachment; filename="chilemon-companion.exe"');

// Validar sesión
Auth::startSession();
if (!Auth::isLoggedIn()) {
    http_response_code(401);
    echo json_encode(['success' => false, 'error' => 'Unauthorized']);
    exit;
}

// Obtener IP de la Pi
$pi_ip = $_SERVER['SERVER_ADDR'] ?? '127.0.0.1';
if ($pi_ip === '127.0.0.1' || $pi_ip === '::1') {
    // Fallback: obtener IP de la interfaz de red
    $pi_ip = gethostbyname(gethostname());
}

// Puerto IAX2
$iax_port = 4569;

// Password del peer companion-app
$secret = 'chilemon2026';

// Generar config.toml
$config = <<<TOML
# ChileMon Companion App Configuration
# Auto-generated by ChileMon Dashboard

[asterisk]
host = "{$pi_ip}"
port = {$iax_port}

[peer]
username = "companion-app"
password = "{$secret}"
skip_registration = true

[audio]
input_device = ""
output_device = ""
sample_rate = 8000
frames_per_buffer = 160

[ws]
bind_host = "127.0.0.1"
bind_port = 9093

[logging]
level = "INFO"
file = ""

TOML;

// Guardar config temporalmente
$config_path = sys_get_temp_dir() . '/chilemon-companion-config.toml';
file_put_contents($config_path, $config);

// Por ahora, solo retornar el config (el .exe se descarga de GitHub)
// En el futuro, se puede empaquetar el .exe con el config
header('Content-Type: application/toml');
header('Content-Disposition: attachment; filename="config.toml"');
header('Content-Length: ' . strlen($config));
echo $config;
exit;
